from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any


class TriggerSeverity(StrEnum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class TriggerCategory(StrEnum):
    FINANCE = "finance"
    MARKETING = "marketing"
    SALES = "sales"
    OPERATIONS = "operations"
    SYSTEM = "system"


class GoalStatus(StrEnum):
    IN_PROGRESS = "in_progress"
    ACHIEVED = "achieved"
    AT_RISK = "at_risk"
    BEHIND = "behind"


@dataclass(frozen=True, slots=True)
class TriggerCondition:
    """Evaluation condition for a business state trigger."""

    metric_key: str
    operator: str  # "<", ">", "<=", ">=", "==", "!=", "pct_change_gt"
    threshold: float
    duration_days: int = 1


@dataclass(slots=True)
class EventTrigger:
    """Configured proactive business event trigger."""

    id: str
    name: str
    description: str
    category: str
    condition: TriggerCondition
    severity: str = TriggerSeverity.WARNING
    enabled: bool = True
    last_checked_at: str | None = None
    last_fired_at: str | None = None
    firing_count: int = 0


@dataclass(slots=True)
class GoalMilestone:
    """Milestone target for a strategic business goal."""

    title: str
    target_value: float
    current_value: float
    unit: str
    target_date: str
    completed: bool = False


@dataclass(slots=True)
class GoalTree:
    """Hierarchical strategic goal tracked by the proactive CEO."""

    id: str
    title: str
    description: str
    category: str
    target_date: str
    status: str = GoalStatus.IN_PROGRESS
    progress_percentage: float = 0.0
    milestones: list[GoalMilestone] = field(default_factory=list)
    child_goals: list[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


@dataclass(frozen=True, slots=True)
class ProactiveInsight:
    """Proactive observation and recommended intervention generated by the CEO."""

    id: str
    trigger_id: str | None
    severity: str
    title: str
    observation: str
    impact_summary: str
    recommended_action: str
    auto_action_capability: str | None = None
    auto_action_arguments: dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    acknowledged: bool = False


@dataclass(frozen=True, slots=True)
class ProactiveEvaluationReport:
    """Comprehensive outcome of a proactive evaluation run."""

    timestamp: str
    triggers_evaluated_count: int
    triggers_fired_count: int
    active_insights_count: int
    goals_tracked_count: int
    critical_alerts: list[str]
    insights: list[ProactiveInsight]
