"""Hermes backwards-compatibility re-export layer for CEO OS Executive Agent."""

from __future__ import annotations

from ceo_agent import (
    DeterministicCeoEngine,
    DeterministicHermesEngine,
    HermesAgentRunTool,
    HermesAIAgent,
    HermesIntegration,
    HermesLlmProtocol,
    HermesMessage,
    HermesModelProvider,
    HermesPromptFormatter,
    HermesReflectionResult,
    HermesReflectiveEngine,
    HermesReflectSynthesizeTool,
    HermesRole,
    HermesRunResult,
    HermesSubagentResult,
    HermesSubagentSpawnTool,
    HermesSubagentSpec,
    HermesSubagentSwarm,
    HermesSynthesizedSkill,
    HermesToolCall,
    HermesToolParser,
    HermesToolResponse,
    HermesTrajectoryExportTool,
    HermesTrajectoryRecord,
    HermesTrajectoryStep,
    HermesTrajectoryStore,
    OpenAiCompatibleCeoEngine,
    OpenAiCompatibleHermesEngine,
    OpenRouterModelProvider,
)

__all__ = [
    "DeterministicCeoEngine",
    "DeterministicHermesEngine",
    "HermesAIAgent",
    "HermesAgentRunTool",
    "HermesIntegration",
    "HermesLlmProtocol",
    "HermesMessage",
    "HermesModelProvider",
    "HermesPromptFormatter",
    "HermesReflectSynthesizeTool",
    "HermesReflectionResult",
    "HermesReflectiveEngine",
    "HermesRole",
    "HermesRunResult",
    "HermesSubagentResult",
    "HermesSubagentSpawnTool",
    "HermesSubagentSpec",
    "HermesSubagentSwarm",
    "HermesSynthesizedSkill",
    "HermesToolCall",
    "HermesToolParser",
    "HermesToolResponse",
    "HermesTrajectoryExportTool",
    "HermesTrajectoryRecord",
    "HermesTrajectoryStep",
    "HermesTrajectoryStore",
    "OpenAiCompatibleCeoEngine",
    "OpenAiCompatibleHermesEngine",
    "OpenRouterModelProvider",
]
